version: '3'

services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      SEARCH_EXPERIENCE_HOST: http://localhost:9001
      DIALOG_EXPERIENCE_HOST: http://localhost:9002
    ports:
    - 4000:3000