version: "3.9"
services:
  tmf629:
    build: ./tmf-services/tmf629-customer
    ports:
        - "4010:4010"
  tmf666:
    build: ./tmf-services/tmf666-account
    ports:
        - "4020:4020"
  subgraph-tmf666:
    build: ./graphql/subgraphs/tmf666-account-gql
    ports:
        - "4001:4001"